[package]
name        = "RetrOS"
version     = "0.0.1"
description = "Retro Linux for old PCs"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
repository  = "https://github.com/ponyatov/RetrOS"
license     = "MIT"
edition     = "2024"

[dependencies]

[target.'cfg(linux)'.dependencies]
libc = "0.2"

[target.x86_64-unknown-linux-gnu.dependencies]

[target.i486-pc-linux-uclibc.dependencies]

[profile.release]
debug = true

[features]

# hw
## hw/x86
pc              = ["i5"]
qemu386         = ["i486"]

# cpu
## cpu/x86
i5              = ["x86_64"]
i486            = ["i386"  ]

# arch
x86_64          = ["linux"]
i386            = ["linux"]

# os
linux           = []
